[asterisk]
host="localhost"
port="5038"
user="admin"
pass="123456"

[mysql]
db_string="user:password@/db"
#user:password@tcp(localhost:5555)/dbname

[memcache]
mem_string="127.0.0.1:11211"

[http]
port="8000"

[log]
path="dialing.log"
