[asterisk]
host="dev.dialingozone.com"
port="1234"
user="trumpen"
pass="foobar"

[mysql]
db_string="dialing:Dl@fj1ra@/dialingdb"
#user:password@tcp(localhost:5555)/dbname

[memcache]
mem_string="127.0.0.1:11211"

[http]
port="8888"

[log]
path="dialing.log"
